### ISSUE TITLE
Nothing happends when try to open oauth browser activity

### ISSUE THREAD

**Issue by sanni-aubergine** [LinusU/flutter_web_auth#46]
When I try to open the auth window for the user to login using the browser, nothing happens.
I think this is because classes in this package are getting removed during the build.

This is the logcat for when it happens.

build info:
Flutter 1.20.0 stable
release mode
package: latest.

`08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: Failed to handle method call
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://auth.ebay.com/... flg=0x30000000 (has extras) }
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2022)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at android.app.Activity.startActivityForResult(Activity.java:4691)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at android.app.Activity.startActivityForResult(Activity.java:4649)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at android.app.Activity.startActivity(Activity.java:5010)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at b.f.g.a.a(Unknown Source:6)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at b.c.b.a.a(Unknown Source:9)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at d.d.a.a.onMethodCall(Unknown Source:107)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at android.os.MessageQueue.nativePollOnce(Native Method)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at android.os.MessageQueue.next(MessageQueue.java:326)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at android.os.Looper.loop(Looper.java:181)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at android.app.ActivityThread.main(ActivityThread.java:7156)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at java.lang.reflect.Method.invoke(Native Method)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
08-25 18:24:34.277 29106 29106 E MethodChannel#flutter_web_auth: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
08-25 18:24:34.279 29106 29156 I flutter : PlatformException(error, No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://auth.ebay.com/... flg=0x30000000 (has extras) }, null)
08-25 18:24:34.280 29106 29156 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type 'PlatformException' is not a subtype of type 'Error'
08-25 18:24:34.280 29106 29156 E flutter : #0      AuthApi.loginWithEbay (package:*******/infrastructure/data/network/apis/auth/auth_api.dart:68)
08-25 18:24:34.280 29106 29156 E flutter : <asynchronous suspension>
08-25 18:24:34.280 29106 29156 E flutter : #1      _ShopProvidersStoreBase.loginWithEbay (package:*******/application/shop_providers/shop_providers_store.dart:32)
08-25 18:24:34.280 29106 29156 E flutter : <asynchronous suspension>
08-25 18:24:34.280 29106 29156 E flutter : #2      AsyncAction.run (package:mobx/src/api/async/async_action.dart:29)
08-25 18:24:34.280 29106 29156 E flutter : <asynchronous suspension>
08-25 18:24:34.280 29106 29156 E flutter : 
08-25 18:24:41.153 29106 29106 D InputMethodManager: prepareNavigationBarInfo() DecorView@3f762f6[MainActivity]
08-25 18:24:41.153 29106 29106 D InputMethodManager: getNavigationBarColor() -855310
08-25 18:24:41.153 29106 29106 V InputMethodManager: Starting input: tba=au.com.bitbot.******* ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
08-25 18:24:41.154 29106 29106 D InputMethodManager: startInputInner - Id : 0
08-25 18:24:41.154 29106 29106 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
08-25 18:24:41.158 29106 29106 D InputTransport: Input channel constructed: fd=107
08-25 18:24:41.158 29106 29106 D InputTransport: Input channel destroyed: fd=114
08-25 18:24:41.166 29106 29106 D ViewRootImpl@caf8391[MainActivity]: ViewPostIme key 1
08-25 18:24:51.585 29106 29106 D ViewRootImpl@caf8391[MainActivity]: ViewPostIme pointer 0
08-25 18:24:51.671 29106 29106 D ViewRootImpl@caf8391[MainActivity]: ViewPostIme pointer 1
`

**Comment by sanni-aubergine** [comment]
I fixed it using proguard rules.
![proguard](https://user-images.githubusercontent.com/61491299/91850866-e0827500-ec7b-11ea-8cd6-aef33d715c4a.png)
-keep class com.linusu.flutter_web_auth.**  { *; }
-keep class com.dexterous.flutterlocalnotifications.**  { *; }
